누적후원금 추가
MineFactory-Resource/CashMF pull request #13
Opened 2022-12-19 08:09 UTC by Seokhun-Yang

2022-12-19 09:08 UTC, LesserJang commented
지금 로직대로라면 오프라인 플레이어의 캐시를 조작했을때, 오프라인 플레이어의 캐시가 저장되고, 캐시는 플레이어가 나갔을때만 사라지니, 오프라인 플레이어의 캐시는 절대 사라지지 않는 것 같은데 맞나요?

2022-12-19 09:15 UTC, Seokhun-Yang commented
오프라인 플레이어의 cash 정보를 수정하면 데이터베이스에서 오프라인 플레이어의 데이터를 로드하여 cache 메모리에 올려둔 뒤 값을 수정하게 되어있으며, 플러그인이 비활성화될 때 cache 메모리에 있는 모든 데이터들을 데이터베이스에 저장하도록 구현되어 있습니다. 따라서 플레이어의 데이터가 저장되는 시점은 온라인 상태인 플레이어가 서버에서 나갈 때 그리고 플러그인이 비활성화될 때 이렇게 2개입니다

2022-12-19 10:40 UTC, LesserJang commented
> 오프라인 플레이어의 cash 정보를 수정하면 데이터베이스에서 오프라인 플레이어의 데이터를 로드하여 cache 메모리에 올려둔 뒤 값을 수정하게 되어있으며, 플러그인이 비활성화될 때 cache 메모리에 있는 모든 데이터들을 데이터베이스에 저장하도록 구현되어 있습니다. 따라서 플레이어의 데이터가 저장되는 시점은 온라인 상태인 플레이어가 서버에서 나갈 때 그리고 플러그인이 비활성화될 때 이렇게 2개입니다

그럼 서버가 꺼지기 전까지 오프라인 플레이어의 캐시는 안사라지고 남아있겠네요. 수정이 필요해보입니다.

2022-12-19 10:42 UTC, Seokhun-Yang commented
저도 수정하는게 더 나을 것이라 생각되네요. 수정하도록 하겠습니다. 감사합니다

2022-12-20 11:16 UTC, LesserJang requested changes

2022-12-20 11:16 UTC, LesserJang commented on src/main/java/net/teamuni/cashmf/data/CashManager.java
> +        }
메인스레드에서 데이터베이스에 접근하시면 안되요

2022-12-20 11:16 UTC, LesserJang commented on src/main/java/net/teamuni/cashmf/data/CashManager.java
> +        }
메인스레드에서 데이터베이스에 접근하시면 안되요

2022-12-20 11:16 UTC, kari0707 commented on src/main/java/net/teamuni/cashmf/CashMF.java
> +    private CashMF instance;
CashMF의 인스턴스를 쓰는 클래스들은 생성자로 인스턴스를 받고 있는데, 이 변수는 static도 아니고 사용이 안되는 거 같습니다.

2022-12-20 11:25 UTC, kari0707 approved these changes

2022-12-20 11:47 UTC, LesserJang approved these changes

2022-12-21 06:47 UTC, merged